"""Small, dependency-free helpers for inspecting untrusted Godot project trees."""

from __future__ import annotations

import os
import re
import stat
from pathlib import Path

REPORT_MARKER = "<!-- generated by godot-skills-publish/tools; safe to replace -->"
TEXT_SUFFIXES = {".gd", ".tscn", ".tres", ".md", ".txt", ".cfg", ".json"}
GODOT_SUFFIXES = (".gd", ".tscn", ".tres", ".res")
SKIP_DIRS = {".git", ".godot", "backups", "backup", "node_modules", "__pycache__", ".venv", "venv"}
SKIP_SUFFIXES = {".zip", ".bak", ".old", ".tmp", ".png", ".jpg", ".jpeg", ".webp", ".ogg", ".wav", ".mp3", ".exe", ".dll", ".pck", ".import"}
MAX_TEXT_BYTES = 2_000_000


def is_link(path: Path) -> bool:
    try:
        info = path.lstat()
    except OSError:
        return True
    return path.is_symlink() or bool(getattr(info, "st_file_attributes", 0) & stat.FILE_ATTRIBUTE_REPARSE_POINT)


def walk_dirs(root: Path):
    """Yield ordinary directories; never descend into links, nested repos or .gdignore trees."""
    root = root.resolve(strict=True)
    stack = [root]
    while stack:
        directory = stack.pop()
        try:
            entries = sorted(directory.iterdir(), key=lambda p: p.name.lower())
        except OSError:
            continue
        if directory != root and (directory / ".git").exists():
            continue
        if directory != root and (directory / ".gdignore").exists():
            continue
        yield directory
        for path in entries:
            if is_link(path):
                continue
            if path.is_dir():
                if path.name.lower() not in SKIP_DIRS and "backup" not in path.name.lower():
                    stack.append(path)


def walk_files(root: Path):
    """Yield ordinary files from safe directories."""
    for directory in walk_dirs(root):
        try:
            entries = sorted(directory.iterdir(), key=lambda p: p.name.lower())
        except OSError:
            continue
        for path in entries:
            if path.is_file() and not is_link(path) and path.suffix.lower() not in SKIP_SUFFIXES and ".backup." not in path.name.lower():
                yield path


def read_text(path: Path) -> str | None:
    try:
        if path.stat().st_size > MAX_TEXT_BYTES:
            return None
        return path.read_text(encoding="utf-8-sig", errors="replace")
    except OSError:
        return None


def require_project(root: Path) -> str:
    config_path = root / "project.godot"
    if is_link(config_path) or not config_path.is_file():
        raise ValueError(f"missing ordinary project.godot: {root}")
    content = read_text(config_path)
    if not content:
        raise ValueError(f"empty or unreadable project.godot: {root}")
    return content


def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def md(value: object) -> str:
    """Keep data as inert inline text, including Markdown metacharacters."""
    return str(value).replace("`", "'").replace("|", "\\|").replace("\n", " ")


def project_files(root: Path) -> dict[str, list[Path]]:
    result = {suffix: [] for suffix in GODOT_SUFFIXES}
    for path in walk_files(root):
        if path.suffix.lower() in result:
            result[path.suffix.lower()].append(path)
    for paths in result.values():
        paths.sort(key=lambda p: rel(p, root))
    return result


def config_value(text: str, key: str) -> str | None:
    match = re.search(r"(?m)^\s*" + re.escape(key) + r"\s*=\s*(.+)$", text)
    return match.group(1).strip().strip('"') if match else None


def config_section(text: str, section: str) -> str:
    match = re.search(r"(?ms)^\[" + re.escape(section) + r"\]\s*\n(.*?)(?=^\[|\Z)", text)
    return match.group(1) if match else ""


def safe_output(project: Path, output: Path, body: str) -> None:
    """Replace only a previously generated Markdown report, never source/input files."""
    output = Path(os.path.abspath(output))
    if output.suffix.lower() != ".md":
        raise ValueError("--output must be an ordinary .md file")
    for component in (output, *output.parents):
        if component.is_symlink() or (component.exists() and is_link(component)):
            raise ValueError(f"--output traverses a link or junction: {component}")
    if output.exists():
        existing = read_text(output)
        if existing is None or not existing.startswith(REPORT_MARKER):
            raise ValueError(f"refusing to overwrite a file not generated by these tools: {output}")
    parent = output.parent
    if not parent.exists() or not parent.is_dir() or is_link(parent):
        raise ValueError("--output parent must already exist and be an ordinary directory")
    output.write_text(REPORT_MARKER + "\n" + body.rstrip() + "\n", encoding="utf-8")


def root_arg(value: str) -> Path:
    root = Path(value).resolve(strict=True)
    if not root.is_dir():
        raise ValueError(f"not a directory: {value}")
    return root


def numbered(items: list[str], limit: int = 60) -> list[str]:
    shown = items[:limit]
    return shown + ([f"- … {len(items) - limit} more omitted"] if len(items) > limit else [])
